/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Reads a parquet buffer. You can pass columns to specify which columns should be read
 * It returns data into arrow IPC format.
 */
export function fromParquetBuffer(parquetBuffer: Buffer, columns: Array<string>): Array<number>
export function fromParquetFile(path: string, columns: Array<string>): Array<number>
